/*
 * Crail-terasort: An example terasort program for Sprak and crail
 *
 * Author: Animesh Trivedi <atr@zurich.ibm.com>
 *         Jonas Pfefferle <jpf@zurich.ibm.com>
 *
 * Copyright (C) 2016, IBM Corporation
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 *
 */

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_ibm_radixsort_NativeRadixSort */

#ifndef _Included_com_ibm_radixsort_NativeRadixSort
#define _Included_com_ibm_radixsort_NativeRadixSort
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_ibm_radixsort_NativeRadixSort
 * Method:    sort
 * Signature: (JIJJ)V
 */
JNIEXPORT void JNICALL Java_com_ibm_radixsort_NativeRadixSort_sort
  (JNIEnv *, jclass, jlong, jint, jlong, jlong);

#ifdef __cplusplus
}
#endif
#endif
